version: "3.10.6"
services:
  postgres:
    image: postgres:14
    restart: on-failure
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_SCHEMA}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${CONTAINER_PORT}:5432"
    volumes:
      - "./:/bootcamp/"
